version: "3.3"
services:
  mvc:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - db
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    #should not expose port when run in prod
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@123
    volumes:
      - learn-aspnet-coremvc:/var/opt/mssql"
volumes:
  learn-aspnet-coremvc:
